<a href="https://colab.research.google.com/github/Kirip/Python/blob/main/Homework_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 4
Part A

In [ ]:
import cvxpy as cp
import numpy as np

def find_closest_permutation_matrix(C):
    n = C.shape[0]
    # Define the variable, which is an n x n matrix.
    P = cp.Variable((n, n), integer=True)

    # Objective is to maximize the inner product <C, P>
    objective = cp.Maximize(cp.trace(C.T @ P))

    # Constraints that define P as a permutation matrix
    constraints = [
        cp.sum(P, axis=0) == 1,  # sum of each column is 1
        cp.sum(P, axis=1) == 1,  # sum of each row is 1
        P >= 0,  # all elements are non-negative
        P <= 1   # all elements are less or equal to 1
    ]

    # Define and solve the problem
    prob = cp.Problem(objective, constraints)
    prob.solve(solver=cp.GLPK_MI)  # Using GLPK solver with mixed integer programming

    # Return the result as a NumPy array
    return P.value

# Example usage
C = np.array([[0.5, 0.1], [0.4, 0.9]])
P = find_closest_permutation_matrix(C)
print("Optimal Permutation Matrix P:")
print(P)


Optimal Permutation Matrix P:
[[1. 0.]
 [0. 1.]]


Part B:



In [ ]:
def solve_lp_relaxation(C):
  n = C.shape[0]
  P = cp.Variable((n,n)) # variable is n x n matrix
  aim = cp.Maximize(cp.trace(C.T @ P)) # maximize the inner product <c,p>
  # constraints that P's row and columns sum to 1 and entries are non-negative
  subject_to = {
      cp.sum(P, axis=0) == 1, # column sum is 1
      cp.sum(P, axis=1) ==1, # row sum is 1
      P >= 0, # non-negative
  }
  question = cp.Problem(aim,subject_to)
  question.solve()

  return np.round(P.value, decimals=3)

C = np.array([
    [1,0,0],
     [0,0,1],
     [0,1,0]])
P_star = solve_lp_relaxation(C)
print("Optimal Point P*:")
print(P_star)

Optimal Point P*:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Part C

The matrices are not a permutation matrix, it means it does not have exactly one entry of 1 in each row and each column, with all other entries being 0, which is a requirement for a permutation matrix. This lack of the permutation matrix properties indicates that the matrix does not represent a permutation of elements and does not have the specific mathematical and computational properties that make permutation matrices useful in certain contexts, such as representing permutations or being orthogonal

In [ ]:
def is_permutation_matrix(C):
    # Check if the matrix is square
    if C.shape[0] != C.shape[1]:
        return False
    # Check if the matrix contains exactly one 1 in each row and column
    row_sums = np.sum(C, axis=1)
    col_sums = np.sum(C, axis=0)
    return np.all(row_sums == 1) and np.all(col_sums == 1)

# Example usage with random 4x4 matrices, repeat 4 times
for _ in range(4):
    C = np.random.rand(4, 4)  # Create a random 4x4 matrix
    P_star = solve_lp_relaxation(C)
    print("Random Matrix C:")
    print(C)
    print("Optimal Point P*:")
    print(P_star)
    print("\n")
    print("Is it a permutation matrix?", is_permutation_matrix(C))

Random Matrix C:
[[0.08424816 0.9269626  0.67065868 0.79252678]
 [0.04784085 0.60042658 0.82747622 0.78570731]
 [0.76349169 0.80743219 0.68263314 0.58409522]
 [0.76766858 0.40311913 0.98936426 0.23262065]]
Optimal Point P*:
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


Is it a permutation matrix? False
Random Matrix C:
[[0.84401918 0.60430384 0.41784673 0.24954582]
 [0.90492158 0.07328409 0.39684956 0.97125819]
 [0.90579619 0.71268818 0.30517918 0.33535527]
 [0.39024856 0.32735188 0.37851205 0.6547918 ]]
Optimal Point P*:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Is it a permutation matrix? False
Random Matrix C:
[[0.42062757 0.55594434 0.38878478 0.35297998]
 [0.30141541 0.3132381  0.95643536 0.52149808]
 [0.98980149 0.4366732  0.38165586 0.67704672]
 [0.2645079  0.39539482 0.73224453 0.48719783]]
Optimal Point P*:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


Is it a permutation matrix? False
Random Matrix C:
[[0.73317705 0.19114

Part D

The optimal point P* from the linear programming LP relaxation is not guaranteed to be a permutation matrix because the LP relaxation allows the entries of P to take any real values between 0 and 1, rather than strictly 0 or 1 as required for permutation matrices. In LP relaxation, the constraints ensure that each row and column sums to 1, but the individual entries can be fractional, meaning P* can include values like 0.3 or 0.5, etc. Therefore, while P* satisfies the row and column sum constraints of a permutation matrix, it does not adhere to the binary constraints, resulting in a matrix that represents a probabilistic or "soft" assignment between elements rather than an exact permutation.

Part E

When the matrix \( C \) has the same value in all its entries, such as in this example, the optimal matrix \( P* \) found by linear programming (LP) might look very similar to \( C \). This happens because each part of \( P \) affects the result equally when \( C \) is uniform, so spreading out values evenly in \( P \) gives the best result. LP relaxation allows \( P \) to have values between 0 and 1 and still make the rows and columns add up to 1. In such cases, the method finds that an evenly distributed \( P \) maximizes the goal, leading to a \( P* \) that looks like \( C \). This shows how a uniform \( C \) leads to a similarly uniform \( P \) when using LP relaxation.

In [ ]:
# A 2 X 2 matrix
C = np.array([
    [0.5,0.5],
     [0.5,0.5]])
P_star = solve_lp_relaxation(C)
print("Optimal Point P*:")
print(P_star)

Optimal Point P*:
[[0.5 0.5]
 [0.5 0.5]]
